SELECT 
      TUDO.CONDVENDA,
      TUDO.CODCLI,
      TUDO.CODPROD,
      TUDO.DT_PEDIDO

FROM 

(
SELECT
  PED.CONDVENDA,
  PED.CODCLI,
  I.CODPROD,
  PED.data as DT_PEDIDO
  
FROM
  PCCLIENT C, PCPRODUT P, PCUSUARI U, PCSUPERV S, PCATIVI A, PCPEDC PED, PCPEDI I, PCPRACA PR, PCFORNEC F, PCREGIAO R, PCSECAO SEC, PCTABPRCLI TABP,
  pcredecliente rede,PCCIDADE CD 
WHERE

  P.CODPROD(+) = I.CODPROD
  AND C.CODREDE=REDE.CODREDE(+) 
  AND TABP.CODCLI(+) = C.CODCLI
  AND C.CODCIDADE=CD.CODCIDADE
  AND U.CODUSUR = PED.CODUSUR
  AND I.NUMPED = PED.NUMPED
  AND U.CODSUPERVISOR = S.CODSUPERVISOR
  AND A.CODATIV = C.CODATV1
  AND PED.CODCLI = C.CODCLI
  AND C.CODPRACA = PR.CODPRACA
  AND P.CODFORNEC = F.CODFORNEC
  AND C.NUMREGIAOCLI = R.NUMREGIAO(+)
  AND P.CODSEC = SEC.CODSEC
  AND PED.CONDVENDA IN (1,5,7,10,11)
  AND PED.dtcancel IS NULL
  AND PED.DATA  >= to_date('01/01/2019','DD/MM/YYYY')
  AND I.DATA  >= to_date('01/01/2019','DD/MM/YYYY')

UNION ALL

SELECT

  PED.CONDVENDA,
  PED.CODCLI,
  CB.CODPRODMP,
  PED.data as DT_PEDIDO

  
FROM
  PCCLIENT C, PCPRODUT P, PCUSUARI U, PCSUPERV S, PCATIVI A, PCPEDC PED,
  PCPRACA PR, PCFORNEC F, PCREGIAO R, PCSECAO SEC, PCPEDICESTA CB, PCTABPRCLI TABP,
  pcredecliente rede,PCCIDADE CD
WHERE

  U.CODUSUR = PED.CODUSUR
  AND C.CODREDE=REDE.CODREDE(+)
  AND TABP.CODCLI(+) = C.CODCLI
  AND C.CODCIDADE=CD.CODCIDADE
  AND PED.NUMPED=CB.NUMPED
  AND P.CODPROD(+)=CB.CODPRODMP
  AND U.CODSUPERVISOR = S.CODSUPERVISOR
  AND A.CODATIV = C.CODATV1
  AND PED.CODCLI = C.CODCLI
  AND C.CODPRACA = PR.CODPRACA
  AND P.CODFORNEC = F.CODFORNEC
  AND C.NUMREGIAOCLI = R.NUMREGIAO(+)
  AND P.CODSEC = SEC.CODSEC
  --AND PED.CONDVENDA = 1
  AND PED.CONDVENDA IN (1,5,7,10,11)
  AND PED.dtcancel IS NULL
  AND PED.DATA  >= to_date('01/01/2019','DD/MM/YYYY')
  
UNION ALL

SELECT
  0 CONDVENDA,
  M.CODCLI,
  M.CODPROD,
  M.DTMOV as DT_PEDIDO

FROM
  PCCLIENT C, PCPRODUT P, PCUSUARI U, PCSUPERV S, PCATIVI A, PCMOV M, PCPRACA PR, PCFORNEC F, PCREGIAO R, PCSECAO SEC, PCTABPRCLI TABP,
  pcredecliente rede,PCCIDADE CD
WHERE
  P.CODPROD(+) = M.CODPROD
  AND C.CODREDE=REDE.CODREDE(+)
  AND TABP.CODCLI(+) = C.CODCLI
  AND C.CODCIDADE=CD.CODCIDADE
  AND U.CODUSUR = M.CODUSUR
  AND U.CODSUPERVISOR = S.CODSUPERVISOR
  AND A.CODATIV = C.CODATV1
  AND M.CODCLI = C.CODCLI
  AND C.CODPRACA = PR.CODPRACA
  AND P.CODFORNEC = F.CODFORNEC
  AND C.NUMREGIAOCLI = R.NUMREGIAO(+)
  AND P.CODSEC = SEC.CODSEC
  AND M.CODOPER = 'ED'
  AND M.CODDEVOL<>123
  AND M.dtcancel IS NULL
  AND M.DTMOV >= to_date('01/01/2019','DD/MM/YYYY')
  ) TUDO